### ISSUE TITLE
Error: refused to execute script

### ISSUE THREAD

**Issue by sql-mahcine** [sapegin/social-likes#168] opened 2015-12-19 08:16 UTC
Refused to execute script from 'http://share.yandex.ru/gpp.xml?url=http%3A%2F%2Fhandyhost.ru%2Fwindows-vps%2F&_=1450512185748' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

**Comment by sapegin** [comment] 2015-12-21 07:29
Duplicate of #165.

**Closed by sapegin** 2015-12-21 07:29 UTC
